version: '3.8'
services:
  spring:
    build:
      context: ./DevOps_Project
      dockerfile: DockerfileBack
    image: spring
    ports:
      - '8080:8080'
    depends_on:
      - mysql
  mysql:
    image: mysql
    container_name: mysql
    restart: always
    volumes:
      - ./mysql:/var/lib/mysql