version: '3.8'
services:
  angular:
    image: ${registry}/angular
    build:
      context: ./DevOps_Project_Front
      dockerfile: Dockerfile-angular
    ports:
      - '80:80'
  spring:
    image: ${registry}/spring
    build:
      context: ./DevOps_Project
      dockerfile: Dockerfile-spring
    ports:
      - '8080:8080'
    depends_on:
      - mysql
  mysql:
    image: mysql
    container_name: mysql
    restart: always
    volumes:
      - ./mysql:/var/lib/mysql
