# Stage 1 : Build the Angular application
FROM node:16-alpine AS builder
WORKDIR /app
COPY package.json ./
RUN npm install
COPY . .
RUN npm run build -- --prod

# Stage 2 : Serve the Angular application with Nginx
FROM nginx:alpine
COPY --from=builder /app/dist/DevOps_Project_Front /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
